DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS; 
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CORREDORA_PROPIEDAD CASCADE CONSTRAINTS;
DROP TABLE TIPO_SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPCION CASCADE CONSTRAINTS;
--DROP TABLE PAGO_SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE TIPO_INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE ESTADO_INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE FOTO_INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE PUBLICACION CASCADE CONSTRAINTS;

/*
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS; 
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CORREDORA_PROPIEDAD CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE SUSCRITO CASCADE CONSTRAINTS; 
DROP TABLE TIPO_INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE ESTADO_INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE INMUEBLE CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR_INMB CASCADE CONSTRAINTS;
DROP TABLE VENTA_INMB CASCADE CONSTRAINTS;
*/

CREATE TABLE REGION (
    ID_REGION INT PRIMARY KEY,
    NOMBRE_REG VARCHAR2(80) NOT NULL
);

CREATE TABLE CIUDAD(
    ID_CIUDAD INT PRIMARY KEY,
    NOM_CIUD VARCHAR2(80) NOT NULL, 
    ID_REGION INT,
    CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE COMUNA(
    ID_COM INT PRIMARY KEY,
    NOM_COM VARCHAR2(100) NOT NULL,
    ID_CIUDAD INT,
    ID_REGION INT,
    CONSTRAINT FK_COMUNA_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE CLIENTE(
    RUT_CLI VARCHAR2(8) PRIMARY KEY,
    DV_CLI CHAR(1) NOT NULL, 
    NOMBRE_CLI VARCHAR2(80) NOT NULL,
    APAT_CLI VARCHAR2(80) NOT NULL,
    AMAT_CLI VARCHAR2(80) NOT NULL,
    DIR_CLI VARCHAR2(100) NOT NULL,
    FECHA_NAC_CLI DATE NOT NULL,
    EMAIL_CLI VARCHAR2(100) NOT NULL,
    CELULAR_CLI VARCHAR2(12) NOT NULL,
    CONTRASEÑA_CLI VARCHAR2(6) NOT NULL,
    ESTADO_SUSCRIPCION_CLI CHAR(1) DEFAULT 'I', --Estado de la suscripción (A: activo, I: inactivo)
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    ID_SUSCR INT,
    CONSTRAINT FK_CLIENTE_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_CLIENTE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_CLIENTE_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION),
    CONSTRAINT FK_CLIENTE_SUSCRIPCION FOREIGN KEY (ID_SUSCR) REFERENCES SUSCRIPCION(ID_SUSCR)
);

CREATE TABLE CORREDORA_PROPIEDAD(
    RUT_CORR VARCHAR2(8) PRIMARY KEY,
    DV_CORR CHAR(1) NOT NULL, 
    NOMBRE_CORR VARCHAR2(100) NOT NULL,
    DIR_CORR VARCHAR2(100) NOT NULL,
    TELEFONO_CORR VARCHAR2(12) NOT NULL,
    EMAIL_CORR VARCHAR2(100) NOT NULL,
    CONTRASEÑA VARCHAR2(6) NOT NULL,
    SITIO_WEB_CORR VARCHAR2(100),
    ESTADO_SUSCRIPCION_CORR CHAR(1) DEFAULT 'I', --Estado de la suscripción (A: activo, I: inactivo)
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    ID_SUSCR INT,
    CONSTRAINT FK_CORREDORA_PROPIEDAD_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_CORREDORA_PROPIEDAD_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_CORREDORA_PROPIEDAD_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION),
    CONSTRAINT FK_CORREDORA_PROPIEDAD_SUSCRIPCION FOREIGN KEY (ID_SUSCR) REFERENCES SUSCRIPCION(ID_SUSCR)
);

CREATE TABLE TIPO_SUSCRIPCION(
    ID_TIPO_SUSCR INT PRIMARY KEY,
    NOMBRE_TIPO_SUSCR VARCHAR2(100) NOT NULL,
    COSTO_TIPO_SUSCR INT
);

CREATE TABLE SUSCRIPCION(
    ID_SUSCR INT PRIMARY KEY,
    FECHA_INICIO_SUCR DATE NOT NULL,
    FECHA_FIN_SUSCR DATE,
    PAGADO CHAR(1) DEFAULT 'I', --Estado de la suscripción (A: activo, I: inactivo)
    ID_TIPO_SUSCR INT,    
    CONSTRAINT FK_SUSCRIPCION_TIPO_SUSCRIPCION FOREIGN KEY (ID_TIPO_SUSCR) REFERENCES TIPO_SUSCRIPCION(ID_TIPO_SUSCR)
);



CREATE TABLE TIPO_INMUEBLE(
    ID_TIPO_INMB INT PRIMARY KEY,
    DESC_TIPO_INMB VARCHAR2(80) NOT NULL    
);

CREATE TABLE ESTADO_INMUEBLE(
    COD_ESTADO_INMB CHAR(1) DEFAULT 'L'  PRIMARY KEY  --Estado de INMUEBLE (L: LIBRE, V: VENDIDO Y A: ARRENDADO)
);


CREATE TABLE INMUEBLE(
    ID_INMB INT PRIMARY KEY,
    DIR_INMB VARCHAR(100) NOT NULL,
    DESC_INMB VARCHAR(100) NOT NULL,
    SUPERFICIE_INMB NUMBER(5,2) NOT NULL,
    DORMITORIO_INMB INT NOT NULL,
    BAÑO_INMB INT NOT NULL,
    PRECIO_INMB INT NOT NULL,
    RUT_CLI VARCHAR(8),
    RUT_CORR VARCHAR(8),
    ID_COM INT,
    ID_CIUDAD INT,
    ID_REGION INT,
    ID_TIPO_INMB INT,
    COD_ESTADO_INMB CHAR(1),
    CONSTRAINT FK_INMUEBLE_CLIENTE FOREIGN KEY (RUT_CLI) REFERENCES CLIENTE(RUT_CLI),
    CONSTRAINT FK_INMUEBLE_CORREDORA_PROPIEDAD FOREIGN KEY (RUT_CORR) REFERENCES CORREDORA_PROPIEDAD(RUT_CORR),
    CONSTRAINT FK_INMUEBLE_COMUNA FOREIGN KEY (ID_COM) REFERENCES COMUNA(ID_COM),
    CONSTRAINT FK_INMUEBLE_CIUDAD FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    CONSTRAINT FK_INMUEBLE_REGION FOREIGN KEY (ID_REGION) REFERENCES REGION(ID_REGION),
    CONSTRAINT FK_INMUEBLE_TIPO_INMUEBLE FOREIGN KEY (ID_TIPO_INMB) REFERENCES TIPO_INMUEBLE(ID_TIPO_INMB),
    CONSTRAINT FK_INMUEBLE_ESTADO_INMUEBLE FOREIGN KEY (COD_ESTADO_INMB) REFERENCES ESTADO_INMUEBLE(COD_ESTADO_INMB)
);


CREATE TABLE FOTO_INMUEBLE (
    ID_FOTO_INMB INT PRIMARY KEY,
    FOTO_INMB_1 VARCHAR2(100),
    FOTO_INMB_2 VARCHAR2(100),
    FOTO_INMB_3 VARCHAR2(100),
    FOTO_INMB_4 VARCHAR2(100),
    ID_INMB INT,
    CONSTRAINT FK_FOTO_INMUEBLE_INMUEBLE FOREIGN KEY (ID_INMB) REFERENCES INMUEBLE(ID_INMB)
);

CREATE TABLE ESTADO_PUBLICACION(
    DESC_ESTADO_PUB VARCHAR2(15)  DEFAULT 'DISPONIBLE' PRIMARY KEY
);

CREATE TABLE PUBLICACION (
    ID_PUB INT PRIMARY KEY,
    DESCRIPCION_PUB VARCHAR2(100) NOT NULL,
    FECHA_PUB DATE NOT NULL,
    DESC_ESTADO_PUB VARCHAR2(15),
    ID_FOTO_INMB INT,
    ID_INMB INT,
    RUT_CORR VARCHAR2(8),
    RUT_CLI VARCHAR2(8),
    CONSTRAINT FK_PUBLICACION_ESTADO_PUBLICACION FOREIGN KEY (DESC_ESTADO_PUB) REFERENCES ESTADO_PUBLICACION(DESC_ESTADO_PUB),
    CONSTRAINT FK_PUBLICACION_FOTO_INMUEBLE FOREIGN KEY (ID_FOTO_INMB) REFERENCES FOTO_INMUEBLE(ID_FOTO_INMB),
    CONSTRAINT FK_PUBLICACION_INMUEBLE FOREIGN KEY (ID_INMB) REFERENCES INMUEBLE(ID_INMB),
    CONSTRAINT FK_PUBLICACION_CORREDORA_PROPIEDAD FOREIGN KEY (RUT_CORR) REFERENCES CORREDORA_PROPIEDAD(RUT_CORR),
    CONSTRAINT FK_PUBLICACION_CLIENTE FOREIGN KEY (RUT_CLI) REFERENCES CLIENTE(RUT_CLI)    
);

