Alter session set "_ORACLE_SCRIPT"=true;
CREATE USER INMOBILIARIA IDENTIFIED BY "1234"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER INMOBILIARIA QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO INMOBILIARIA;
GRANT "RESOURCE" TO INMOBILIARIA;
ALTER USER INMOBILIARIA DEFAULT ROLE "RESOURCE";